# action.yml
# docker push if formed as so:
# DOCKER_REGISTRY_URL/OWNER/REPOSITORY/IMAGE_NAME:VERSION
# ex:
# docker.pkg.github.com/ryanjfrizzell/action-bpd/bpd:VERSION
name: 'Build and Publish Dockerfile'
description: 'simple build an publish of Dockerfile'
author: 'Ryan Frizzell'
branding: 
  icon: anchor
  color: orange
inputs:
  docker_registry_url:
    description: 'the url your registry is located at, used for docker login, ex: docker.pkg.github.com'
    required: true
    default: ''
  docker_registry_owner: 
    description: 'the owner for the registry, ex: ryanjfrizzell'
    required: true
    default: ''
  docker_repository:
    description: 'repository of the image, ex: action-bpd  '
    required: true
    default: ''
  docker_image:
    description: 'image name to use'
    required: true
    default: ''
  docker_username:
    description: 'username needed to login to your registry'
    required: true
  docker_password:
    description: 'password needed to login to your registry'
    required: true
  dockerfile:
    description: 'the location of your dockerfile'
    default: 'Dockerfile'
    required: true
  docker_image_tag:
    description: 'the tag version you would like to use'
    default: 'latest'
    required: true
  docker_registry:
    description: 'use this to override the formation of the image url'
    default: ''
    required: true
  dockerhub:
    description: 'are you trying to push to dockerhub? [true/false]'
    default: 'false'
    required: true
  pushd: 
    description: 'optionally pushd to a directory before execution'
    default: ''
    required: false

outputs:
  imageinfo: 
    description: 'the image created and pushed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docker_registry_url }}
    - ${{ inputs.docker_registry_owner }}
    - ${{ inputs.docker_repository }}
    - ${{ inputs.docker_image }}
    - ${{ inputs.docker_username }}
    - ${{ inputs.docker_password }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.docker_image_tag }}
    - ${{ inputs.docker_registry }}
    - ${{ inputs.dockerhub }}
    - ${{ inputs.pushd }}
